// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpjU6GJdq3JLK6egK7DB61wxOMRmV-Is',
    appId: '1:240182553988:web:836119d9824886766781d1',
    messagingSenderId: '240182553988',
    projectId: 'pdf-image-15918',
    authDomain: 'pdf-image-15918.firebaseapp.com',
    databaseURL: 'https://pdf-image-15918-default-rtdb.firebaseio.com',
    storageBucket: 'pdf-image-15918.appspot.com',
    measurementId: 'G-P517WQ46ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Au1V03yUdMMuIWdOpEIJ7haqODX2jcc',
    appId: '1:240182553988:android:e28b9feded2c4a606781d1',
    messagingSenderId: '240182553988',
    projectId: 'pdf-image-15918',
    databaseURL: 'https://pdf-image-15918-default-rtdb.firebaseio.com',
    storageBucket: 'pdf-image-15918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqxl2WfsBArXvZ7icuba4osWU51mjEFnw',
    appId: '1:240182553988:ios:3d7eb512812405496781d1',
    messagingSenderId: '240182553988',
    projectId: 'pdf-image-15918',
    databaseURL: 'https://pdf-image-15918-default-rtdb.firebaseio.com',
    storageBucket: 'pdf-image-15918.appspot.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqxl2WfsBArXvZ7icuba4osWU51mjEFnw',
    appId: '1:240182553988:ios:163caa67301ebe6e6781d1',
    messagingSenderId: '240182553988',
    projectId: 'pdf-image-15918',
    databaseURL: 'https://pdf-image-15918-default-rtdb.firebaseio.com',
    storageBucket: 'pdf-image-15918.appspot.com',
    iosBundleId: 'com.example.adminApp.RunnerTests',
  );
}
